[phases.setup]
nixPkgs = ["nodejs_20"]
aptPkgs = ["curl", "unzip"]

[phases.install]
cmds = [
  "curl -fsSL https://bun.sh/install | bash && mv $HOME/.bun/bin/bun /usr/local/bin/bun && chmod +x /usr/local/bin/bun",
  "/usr/local/bin/bun install"
]

[phases.build]
cmds = ["/usr/local/bin/bun run build"]

[start]
cmd = "/usr/local/bin/bun run start"
