[phases.setup]
nixPkgs = ["nodejs_20"]
aptPkgs = ["curl", "unzip"]

[phases.install]
cmds = [
  "curl -fsSL https://bun.sh/install | bash && sudo cp $HOME/.bun/bin/bun /usr/local/bin/bun",
  "bun install"
]

[phases.build]
cmds = ["bun run build"]

[start]
cmd = "bun run start"
