[phases.setup]
nixPkgs = ["nodejs_20"]
aptPkgs = ["curl", "unzip"]

[phases.install]
cmds = [
  "curl -fsSL https://bun.sh/install | bash && cp -r $HOME/.bun /tmp/bun-backup",
  "cp -r /tmp/bun-backup $HOME/.bun && $HOME/.bun/bin/bun install"
]

[phases.build]
cmds = ["$HOME/.bun/bin/bun run build"]

[start]
cmd = "$HOME/.bun/bin/bun run start"
